export const facilities = {
  tx_122_4: false,
  rx_122_4: false,
  tx_120_55: false,
  rx_120_55: false,
  awos: false,
  signal_lamp: false,
  crash_bell: false,
  sirine: false,
  binocular: false,
  vscs: false,
  navaid_monitor: false,
  fids: false,
  afls: false,
  aftn: false,
  iais: false,
  ht_1: false,
  ht_2: false,
  ht_3: false,
  phone_coord: false,
  phone_tele: false,
}
